/* Generated by Together */ 
 
package org.sorbet.CORBA; 
 
/** This exception is thrown when asked operation is non defined 
 * @author Equipe ORB&POA&Millo Jean-vivien
 * @version 2.5
 */ 
public class MARSHAL extends org.sorbet.CORBA.SystemException 
{ 
    /** Constructs an Exception without a message. */ 
    public MARSHAL() 
    { 
        super("MARSHAL ERROR"); 
                 
    } 
 
    /** 
     * Constructs an Exception with a detailed message. 
     * @param Message The message associated with the exception. 
     */ 
    public MARSHAL(String message) 
    { 
        super(message); 
         
    } 
} 
